import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class f15 extends javax.swing.JFrame {

    /**
     * Creates new form f15
     */
    public f15() {
        initComponents();
        
        {{ try
{Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","sg");
Statement stmt=(Statement)con.createStatement();
String query="Select * from username;";
ResultSet rs = stmt.executeQuery(query);
while(rs.next())
{String nm=rs.getString("USERNAME");
L3.setText(nm);}
}
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());}
}

DefaultTableModel model=(DefaultTableModel)T.getModel();
int rows=model.getRowCount();
if(rows>0)
{for(int i=0;i<rows;i++)
model.removeRow(0);}
try{Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","sg");
Statement stmt=(Statement)con.createStatement();
String query="Select * from bill;";
ResultSet rs = stmt.executeQuery(query);
while(rs.next())
{String i=rs.getString("ITEM");
double p=rs.getDouble("PRICE");
double q=rs.getDouble("QUANTITY");
String np=rs.getString("NET_PRICE");
model.addRow(new Object[] {i,p,q,np});}
}catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());}

try{Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","sg");
Statement stmt=(Statement)con.createStatement();
String sql="Select sum(net_price) from bill;";
ResultSet rs= stmt.executeQuery(sql);
if(rs.next()){
String sum=rs.getString("sum(net_price)");
t1.setText(sum);
double TA=Double.parseDouble(t1.getText());
double tax=0.18*TA;
double namt=TA+tax;
t2.setText(""+namt);
}}
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());}
}


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        T = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        C1 = new javax.swing.JComboBox();
        t2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        L3.setForeground(new java.awt.Color(102, 0, 102));
        L3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 360, 70));

        T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ITEM", "PRICE", "QUANTITY", "NET PRICE"
            }
        ));
        jScrollPane1.setViewportView(T);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 850, 230));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("18%");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 110, 30));

        C1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT:", "NON_VEG_THE_GIANT_DINNER_BOX", "VEG_THE_GIANT_DINNER_BOX", "ULTIMATE PANEER", "ULTIMATE VEGGIE", "FARMHOUSE", "COUNTRY SPECIAL", "GOLDEN CORN", "PANEER VEGORAMA", "CHICKEN GOLDEN DELIGHT", "NON VEG SUPREME", "CHICKEN FIESTA", "PERI PERI CHICKEN", "PANEER BIRIZZA", "VEGGIE BIRIZZA", "CHICKEN BIRIZZA", "CHOCO TRUFFLE CAKE", "CHOCO MOUSSE", "CHOCO CHIP LAVA COOKIE" }));
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 280, 50));

        t2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 280, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NET AMOUNT");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 190, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DELETE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("AMOUNT");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 110, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TAX");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 110, 30));

        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 280, 40));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton12.setText("EXIT");
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 150, 50));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton13.setText("HOME");
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 150, 50));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
   this.setVisible(false);
        new f8().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 try{Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","sg");
Statement stmt=(Statement)con.createStatement();
String N=L3.getText();
String namt=t2.getText();
String query="DELETE FROM BILL;";
stmt.executeUpdate(query);
String query1="INSERT INTO HISTORY VALUES('"+N+"','"+namt+"');";
JOptionPane.showMessageDialog(this,"THANKS  "+N+"  FOR  VISITING" + "\n" +" YOUR  BILL  AMOUNT  IS: " + namt + " ");
System.exit(0);
}
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());}  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
try{Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","sg");
Statement stmt=(Statement)con.createStatement();
String IT=(String)C1.getSelectedItem();
String query="Delete from bill where ITEM='"+IT+"';";
stmt.executeUpdate(query);
String query1="Select * from bill;";
DefaultTableModel model=(DefaultTableModel)T.getModel();
int rows=model.getRowCount();
if(rows>0)
{for(int i=0;i<rows;i++)
model.removeRow(0);}
ResultSet rs = stmt.executeQuery(query1);
while(rs.next())
{String i=rs.getString("ITEM");
double p=rs.getDouble("PRICE");
double q=rs.getDouble("QUANTITY");
String np=rs.getString("NET_PRICE");
model.addRow(new Object[] {i,p,q,np});
}}
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());}

  try{Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","sg");
Statement stmt=(Statement)con.createStatement();
String sql="Select sum(net_price) from bill;";
ResultSet rs= stmt.executeQuery(sql);
if(rs.next()){
String sum=rs.getString("sum(net_price)");
t1.setText(sum);
double TA=Double.parseDouble(t1.getText());
double tax=0.18*TA;
double namt=TA+tax;
t2.setText(""+namt);
}}
  catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox C1;
    private javax.swing.JLabel L3;
    private javax.swing.JTable T;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
